import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalHeader from "./components/ConditionalHeader";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Siddhanath",
    description: "Generated by create next app",
    icons: {
        icon: [{ url: "/sdt.png", type: "image/png" }],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="bg-white">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ConditionalHeader />
                {children}
            </body>
        </html>
    );
}
